added changes

diff --git a/.github/workflows/ci_c_pipeline.yaml b/.github/workflows/ci_c_pipeline.yaml
--- a/.github/workflows/ci_c_pipeline.yaml
+++ b/.github/workflows/ci_c_pipeline.yaml
@@ -112,13 +112,13 @@ jobs:
 
       - name: Deploy Idle Version
         run: |
-          kubectl apply -f k8s/deployment-${IDLE_VERSION}.yaml
+          kubectl apply -f k8s/deployment-${{ env.IDLE_VERSION }}.yaml
 
       - name: Wait for Idle Deployment to be Ready (Optional Rollback)
         run: |
-          if kubectl get deployment ${SERVICE}-${IDLE_VERSION} > /dev/null 2>&1; then
-            if ! kubectl rollout status deployment/${SERVICE}-${IDLE_VERSION} --timeout=120s; then
-              echo "Rollout failed for ${SERVICE}-${IDLE_VERSION}. Keeping ${CURRENT_VERSION} live."
+          if kubectl get deployment ${SERVICE}-${{ env.IDLE_VERSION }} > /dev/null 2>&1; then
+            if ! kubectl rollout status deployment/${SERVICE}-${{ env.IDLE_VERSION }} --timeout=120s; then
+              echo "Rollout failed for ${SERVICE}-${{ env.IDLE_VERSION }}. Keeping ${CURRENT_VERSION} live."
               exit 1
             fi
           else
@@ -128,16 +128,16 @@ jobs:
       - name: Create or Patch Service to Point to Idle Version
         run: |
           if kubectl get service ${SERVICE} > /dev/null 2>&1; then
-            echo "Patching service ${SERVICE} to point to ${IDLE_VERSION}"
-            kubectl patch service ${SERVICE} -p "{\"spec\":{\"selector\":{\"app\":\"${SERVICE}\",\"version\":\"${IDLE_VERSION}\"}}}"
+            echo "Patching service ${SERVICE} to point to ${{ env.IDLE_VERSION }}"
+            kubectl patch service ${SERVICE} -p "{\"spec\":{\"selector\":{\"app\":\"${SERVICE}\",\"version\":\"${{ env.IDLE_VERSION }}\"}}}"
           else
             echo " Creating service ${SERVICE} for the first time"
             kubectl apply -f k8s/service.yaml
-            kubectl patch service ${SERVICE} -p "{\"spec\":{\"selector\":{\"app\":\"${SERVICE}\",\"version\":\"${IDLE_VERSION}\"}}}"
+            kubectl patch service ${SERVICE} -p "{\"spec\":{\"selector\":{\"app\":\"${SERVICE}\",\"version\":\"${{ env.IDLE_VERSION }}\"}}}"
           fi
 
       - name: Success Message
-        run: echo "Successfully switched ${SERVICE} to ${IDLE_VERSION}"
+        run: echo "Successfully switched ${SERVICE} to ${{ env.IDLE_VERSION }}"
 
   deploy_aggregator:
     if: ${{ inputs.aggregator_service == 'true' }}
